# Generated by Django 2.2.3 on 2020-10-18 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.PositiveIntegerField()),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('justificante', models.FileField(upload_to='b_activities_app/archivos')),
                ('estado', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('anio_academico', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='control_matricula',
            fields=[
                ('id_matricula', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.PositiveIntegerField()),
                ('periodo_matricula', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Control Matricula',
                'verbose_name_plural': 'Controles Matricula',
            },
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='b_activities_app.actividad')),
                ('id_programa', models.PositiveIntegerField()),
                ('horas_asignadas', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Curso / Direccion de proyectos / Revision de proyectos',
                'verbose_name_plural': 'Cursos / Direcciones de proyectos / Revisiones de proyectos',
            },
            bases=('b_activities_app.actividad',),
        ),
        migrations.CreateModel(
            name='estanciaInvestigacion',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='b_activities_app.actividad')),
                ('id_ins', models.PositiveIntegerField()),
                ('proposito', models.CharField(max_length=25)),
                ('responsable', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estancia de investigación en otras instituciones',
                'verbose_name_plural': 'Estancias de investigación en otras instituciones',
            },
            bases=('b_activities_app.actividad',),
        ),
        migrations.CreateModel(
            name='exposicionResultados',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='b_activities_app.actividad')),
                ('modalidad', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=20)),
                ('lugar', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Exposición de resultados parciales de investigación',
                'verbose_name_plural': 'Exposiciónes de resultados parciales de investigación',
            },
            bases=('b_activities_app.actividad',),
        ),
        migrations.CreateModel(
            name='parcipacionProyecto',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='b_activities_app.actividad')),
                ('id_linea_invs', models.PositiveIntegerField()),
                ('id_investigador', models.PositiveIntegerField()),
                ('lugar', models.CharField(max_length=50)),
                ('codigoVRI', models.IntegerField()),
                ('convocatoria', models.CharField(max_length=50)),
                ('tipo_convocatoria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Participación en proyecto de investigación',
                'verbose_name_plural': 'Participaciónes en proyectos de investigación',
            },
            bases=('b_activities_app.actividad',),
        ),
        migrations.CreateModel(
            name='ponenciaCongreso',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='b_activities_app.actividad')),
                ('id_ins', models.PositiveIntegerField()),
                ('lugar', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Ponencia en congreso / Simposio / Jornada',
                'verbose_name_plural': 'Ponencias en congresos / Simposios / Jornadas',
            },
            bases=('b_activities_app.actividad',),
        ),
        migrations.CreateModel(
            name='publicacion',
            fields=[
                ('actividad_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='b_activities_app.actividad')),
                ('tipo_pub', models.CharField(max_length=100)),
                ('autores', models.CharField(max_length=255)),
                ('datos_generales', models.CharField(max_length=255)),
                ('editorial', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
            bases=('b_activities_app.actividad',),
        ),
        migrations.CreateModel(
            name='premio',
            fields=[
                ('id_premio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_activities_app.actividad')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
            },
        ),
    ]
