# Generated by Django 2.2.3 on 2020-10-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('b_activities_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='id_evaluacion_coo',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='id_evaluacion_dir',
        ),
        migrations.CreateModel(
            name='premio',
            fields=[
                ('id_premio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_activities_app.actividad')),
            ],
            options={
                'verbose_name': 'Premio',
                'verbose_name_plural': 'Premios',
            },
        ),
    ]
